---
title: "Previsió de professorat a secundària"
author: Ivàlua
format: dashboard
server: shiny
---


```{r}
#| context: setup

library(tidyverse)
library(dplyr)
library(tidylog)
library(ggplot2)
library(lubridate)
library(purrr)
library(haven)
library(readxl)
library(readxl)
library(here)
library(janitor)
library(ggpubr)
library(stringdist)
library(sjmisc)
library(jtools)
library(modelsummary)
library(broom)
library(gt)
library(patchwork)
library(sf)
library(collapse)
library(networkD3)
library(labelled)
library(openxlsx)
library(arrow)
library(tsibble) # ARIMA
library(fable) # ARIMA
library(shiny)
library(ggiraph)


paleta_ivalua <- c("#002C4B", "#40617a", "#4A5C83", "#6782a1",
                   "#74b2c0", "#81c6d0","#bcdfe4", "#e5e4e4",
                   "#fac5c5", "#d72132", "#C0001B")

library(extrafont)
loadfonts(quiet = TRUE)

theme_ivalua <- function(base_size = 11,
                         base_family = "Roboto",
                         base_line_size = base_size / 22,
                         base_rect_size = base_size / 22,
                         axis_text_x = TRUE,
                         axis_text_y = FALSE,
                         axis_titles = FALSE) {
  t <- ggplot2::theme_classic(
    base_size = base_size,
    base_family = base_family,
    base_line_size = base_line_size,
    base_rect_size = base_rect_size
  ) + # need to eventually change to replace()
    ggplot2::theme(
      plot.title = ggplot2::element_text(
        family = base_family,
        face = "bold",
        hjust = 0
      ),
      plot.subtitle = ggplot2::element_text(
        family = base_family,
        face = "plain"
      ),
      plot.caption = ggplot2::element_text(
        family = base_family,
        size = base_size + 1,
        hjust = 0,
        vjust = 1.2,
        face = "plain"
      ),
      axis.line.x = ggplot2::element_blank(),
      axis.ticks.x = ggplot2::element_blank(),
      axis.line.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      strip.background = ggplot2::element_blank(),
      legend.position = "bottom",
      strip.text.x = ggplot2::element_text(
        face = "bold",
        size = base_size,
        angle = 0
      ),
      strip.text.y.left = ggplot2::element_text(
        face = "bold",
        size = base_size,
        angle = 0
      ),
      strip.text.y.right = ggplot2::element_text(
        face = "bold",
        size = base_size,
        angle = 0
      ),
      axis.text.x = ggplot2::element_text(
        family = base_family,
        face = "plain",
        size = base_size
      ),
      axis.text.y = ggplot2::element_text(
        family = base_family,
        face = "plain",
        size = base_size
      ),
      axis.title.x = ggplot2::element_text(
        family = base_family,
        face = "plain"
      ),
      axis.title.y = ggplot2::element_text(
        family = base_family,
        face = "plain"
      )
    )
  if(!axis_titles){
    t <- t +
      theme(axis.title.x = ggplot2::element_blank(),
            axis.title.y = ggplot2::element_blank())
  }
  if(!axis_text_y){
    t <- t +
      theme(axis.text.y = ggplot2::element_blank())
  }
  if(!axis_text_x){
    t <- t +
      theme(axis.text.x = ggplot2::element_blank())
  }
  return(t)
}


anys <- 2018:2032
oferta <- seq(1000, 1500, length.out = length(anys))   # augmenta cada any
demanda <- seq(1600, 1000, length.out = length(anys))  # disminueix cada any

# Crear el data frame
panell <- data.frame(
  any = anys,
  oferta = round(oferta),
  demanda = round(demanda)) %>%
  # mutate(demanda = demanda + 1000) %>%
  uncount(5, .id = "especialitat") %>%
  uncount(2, .id = "ratio") %>%
  mutate(ratio = ifelse(
    ratio == 1,
    "Fixe",
    "Flexible")) %>%
  uncount(3, .id = "escenari_entrada") %>%
  mutate(escenari_entrada = case_when(
    escenari_entrada == 1 ~ "Baix",
    escenari_entrada == 2 ~ "Mig",
    escenari_entrada == 3 ~ "Alt")) %>%
  uncount(3, .id = "escenari_alumnes") %>%
  mutate(escenari_alumnes = case_when(
    escenari_alumnes == 1 ~ "Baix",
    escenari_alumnes == 2 ~ "Mig",
    escenari_alumnes == 3 ~ "Alt")) %>%
  uncount(2, .id = "concertada_privada") %>%
  mutate(concertada_privada = case_when(
    concertada_privada == 1 ~ "Pública",
    concertada_privada == 2 ~ "Concertada"))

panell_tot <- panell %>% 
  group_by(any, ratio, escenari_entrada,
           escenari_alumnes,concertada_privada) %>% 
  summarise(
    across(.cols = c(oferta, demanda),
           .fns = sum))


```

##  {.sidebar}

```{r}

#| context: server


sliderInput("curs_range", "Selecciona els cursos:",
            min = min(panell$any),
            max = max(panell$any),
            value = c(min(panell$any), max(panell$any)),
            step = 1,
            sep = "")

selectInput(
  "ratio_filter", 
  "Selecciona els escenaris:",
  choices = levels(as.factor(panell$ratio)),
  selected = levels(as.factor(panell$ratio))[1]
)

selectInput(
  "escenari_entrada_filter", 
  "Selecciona l'escenari d'entrada:",
  choices = levels(as.factor(panell$escenari_entrada)),
  selected = levels(as.factor(panell$escenari_entrada))[1]
)

selectInput(
  "escenari_alumnes_filter", 
  "Selecciona l'escenari demogràfic:",
  choices = levels(as.factor(panell$escenari_alumnes)),
  selected = levels(as.factor(panell$escenari_alumnes))[1]
)

selectInput(
  "concertada_filter", 
  "Selecciona l'evolució de la concertada:",
  choices = levels(as.factor(panell$concertada_privada)),
  selected = levels(as.factor(panell$concertada_privada))[1]
)

checkboxGroupInput(
  "especialitat_filter", 
  "Selecciona l'especialitat:",
  choices = levels(as.factor(panell$especialitat)),
  selected = levels(as.factor(panell$especilaitat))[1]
)



```

# Gràfic total


```{r}
plotOutput("grafic_total")
```

```{r}
#| context: server

output$grafic_total <- renderPlot({
  
  req(input$curs_range)
  
  # Filtrar les dades segons els inputs seleccionats
  dades_filtrades <- panell_tot %>%
    filter(ratio == input$ratio_filter,
           escenari_entrada == input$escenari_entrada_filter,
           escenari_alumnes  == input$escenari_alumnes_filter,
           concertada_privada == input$concertada_filter,
           any >= input$curs_range[1],
           any <= input$curs_range[2]) %>% 
    ungroup()
  
  # Crear el gràfic amb ggplot
  dades_filtrades %>%
  ggplot(aes(x = any)) +
  geom_line(
    data = dades_filtrades %>% filter(any >= 2025),
    aes(y = oferta),
    size = 1,
    linetype = "dashed",
    color = paleta_ivalua[1]) +
  geom_line(
    data = dades_filtrades %>% filter(any <= 2025),
    aes(y = oferta, color = "Oferta"),
    size = 1) +
  geom_line(
    data = dades_filtrades %>% filter(any >= 2025),
    aes(y = demanda),
    size = 1,
    color = paleta_ivalua[10],
    linetype = "dashed") +
  geom_line(
    data = dades_filtrades %>% filter(any <= 2025),
    aes(y = demanda, color = "Demanda"),
    size = 1) +
  scale_color_manual(values = c("Demanda" =  paleta_ivalua[10],
                                "Oferta" = paleta_ivalua[1])) +
  geom_ribbon(
    data = dades_filtrades %>% filter(oferta > demanda),
    aes(ymin = demanda, ymax = oferta),
              fill = paleta_ivalua[11], alpha = .3) +
  # Linea en la intersecció
  geom_vline(xintercept = dades_filtrades %>%
               ungroup() %>% 
               filter(oferta > demanda) %>%
               mutate(any = as.numeric(any)) %>% 
               slice_min(any) %>% 
               pull(any),
             linetype = "dashed",
             alpha = .8) +
  # # Any d'intersecció
  geom_text(aes(
    x = ifelse(dades_filtrades$oferta > dades_filtrades$demanda,
               dades_filtrades %>% filter(oferta > demanda) %>% slice_min(any) %>% pull(any) + .5,
               min(dades_filtrades$any)),
    y = max(dades_filtrades$demanda),
    label = ifelse(dades_filtrades$oferta > dades_filtrades$demanda,
                   dades_filtrades %>% filter(oferta > demanda) %>% slice_min(any) %>% pull(any),
                   "")))  +
  # # # Alerta
  geom_text(aes(
    x = ifelse(dades_filtrades$oferta > dades_filtrades$demanda,
               dades_filtrades %>% filter(oferta > demanda) %>% slice_min(any) %>% pull(any) + 3,
               min(dades_filtrades$any)),
    y = ifelse(dades_filtrades$oferta > dades_filtrades$demanda,
               dades_filtrades %>% filter(oferta > demanda) %>% slice_min(oferta) %>% pull(oferta),
               min(dades_filtrades$any)),
    label = ifelse(dades_filtrades$oferta > dades_filtrades$demanda,
                   "Dèficit de professorat",
                   ""),
    size = 44),
    color = paleta_ivalua[11]) +
  scale_y_continuous(limits = c(
    (min(min(dades_filtrades$oferta), min(dades_filtrades$demanda))),
    (max(max(dades_filtrades$oferta), max(dades_filtrades$demanda))))) +
  theme_ivalua(axis_text_y = T) +
  labs(color = "")

    
})
```


# Gràfic per especialitat

```{r}
plotOutput("grafic_especialitat")
```

```{r}
#| context: server

output$grafic_especialitat <- renderPlot({
  
  req(input$curs_range)
  
  # Filtrar les dades segons els inputs seleccionats
  dades_filtrades <- panell %>%
    filter(ratio == input$ratio_filter,
           escenari_entrada == input$escenari_entrada_filter,
           escenari_alumnes  == input$escenari_alumnes_filter,
           concertada_privada == input$concertada_filter,
           especialitat %in% input$especialitat_filter,
           any >= input$curs_range[1],
           any <= input$curs_range[2])
  
  # Crear el gràfic amb ggplot
  dades_filtrades %>%
  ggplot(aes(x = any)) +
  geom_line(
    data = dades_filtrades %>% filter(any >= 2025),
    aes(y = oferta),
    size = 1,
    linetype = "dashed",
    color = paleta_ivalua[1]) +
  geom_line(
    data = dades_filtrades %>% filter(any <= 2025),
    aes(y = oferta, color = "Oferta"),
    size = 1) +
  geom_line(
    data = dades_filtrades %>% filter(any >= 2025),
    aes(y = demanda),
    size = 1,
    color = paleta_ivalua[10],
    linetype = "dashed") +
  geom_line(
    data = dades_filtrades %>% filter(any <= 2025),
    aes(y = demanda, color = "Demanda"),
    size = 1) +
  scale_color_manual(values = c("Demanda" =  paleta_ivalua[10],
                                "Oferta" = paleta_ivalua[1])) +
  geom_ribbon(
    data = dades_filtrades %>% filter(oferta > demanda),
    aes(ymin = demanda, ymax = oferta),
              fill = paleta_ivalua[11], alpha = .3) +
  # Linea en la intersecció
  geom_vline(xintercept = dades_filtrades %>% filter(oferta > demanda) %>% slice_min(any) %>% pull(any),
             linetype = "dashed",
             alpha = .8) +
  # Any d'intersecció
  geom_text(aes(
    x = ifelse(dades_filtrades$oferta > dades_filtrades$demanda,
               dades_filtrades %>% filter(oferta > demanda) %>% slice_min(any) %>% pull(any) + .5,
               min(dades_filtrades$any)),
    y = max(dades_filtrades$demanda),
    label = ifelse(dades_filtrades$oferta > dades_filtrades$demanda,
                   dades_filtrades %>% filter(oferta > demanda) %>% slice_min(any) %>% pull(any),
                   "")))  +
  # # Alerta
  # geom_text(aes(
  #   x = ifelse(dades_filtrades$oferta > dades_filtrades$demanda,
  #              dades_filtrades %>% filter(oferta > demanda) %>% slice_min(any) %>% pull(any) + 3,
  #              min(dades_filtrades$any)),
  #   y = ifelse(dades_filtrades$oferta > dades_filtrades$demanda,
  #              dades_filtrades %>% filter(oferta > demanda) %>% slice_min(oferta) %>% pull(oferta),
  #              min(dades_filtrades$any)),
  #   label = ifelse(dades_filtrades$oferta > dades_filtrades$demanda,
  #                  "Dèficit de professorat",
  #                  "")),
  #   color = paleta_ivalua[11]) +
  scale_y_continuous(limits = c(
    (min(min(dades_filtrades$oferta), min(dades_filtrades$demanda))),
    (max(max(dades_filtrades$oferta), max(dades_filtrades$demanda))))) +
  theme_ivalua(axis_text_y = T) +
  labs(color = "") +
    facet_wrap(~especialitat,
               ncol = 3)

    
})
```
