---
title: "Model de Previsió de Necessitats de Professorat"
author: Ivàlua
format: dashboard
server: shiny
---


```{r}
#| context: setup

source("0. Libs.R")

source("1. Funcions.R")


```

##  {.sidebar}

```{r}

#| context: server


sliderInput("curs_range", "Selecciona els cursos:",
            min = min(panell$curs),
            max = max(panell$curs),
            value = c(min(panell$curs), max(panell$curs)),
            step = 1,
            sep = "")

selectInput(
  "ratio_filter", 
  "Selecciona la ràtio alumnat-professorat:",
  choices = levels(as.factor(panell$ratio)),
  selected = levels(as.factor(panell$ratio))[1]
)

selectInput(
  "escenari_entrada_filter", 
  "Selecciona l'escenari d'entrades a la borsa:",
  choices = levels(as.factor(panell$escenari_entrada)),
  selected = levels(as.factor(panell$escenari_entrada))[1]
)

selectInput(
  "escenari_alumnes_filter", 
  "Selecciona l'escenari demogràfic:",
  choices = levels(as.factor(panell$escenari_alumnes)),
  selected = levels(as.factor(panell$escenari_alumnes))[1]
)

selectInput(
  "concertada_filter", 
  "Selecciona l'evolució de la concertada:",
  choices = levels(as.factor(panell$concertada_privada)),
  selected = levels(as.factor(panell$concertada_privada))[1]
)

checkboxGroupInput(
  "especialitat_filter", 
  "Selecciona l'especialitat:",
  choices = levels(as.factor(panell$especialitat)),
  selected = levels(as.factor(panell$especialitat))[1]
)



```



# Gràfic total


```{r}
plotOutput("grafic_total")
```

```{r}
#| context: server

output$grafic_total <- renderPlot({
  
  req(input$curs_range)
 
  # Filtrar les dades segons els inputs seleccionats 
  dades_filtrades <- panell_tot %>%
    filter(ratio == input$ratio_filter,
           escenari_entrada == input$escenari_entrada_filter,
           escenari_alumnes  == input$escenari_alumnes_filter,
           concertada_privada == input$concertada_filter,
           curs >= input$curs_range[1],
           curs <= input$curs_range[2]) %>% 
    ungroup() %>% 
    mutate(nivell = factor(nivell, levels = c("Infantil i primària", "ESO i batxillerat")))
  
  last_obs <- dades_filtrades %>% 
    filter(curs == max(curs))
    
  
  # Crear el gràfic amb ggplot
  dades_filtrades %>%
    ggplot(aes(x = curs)) +
    geom_line(
      data = dades_filtrades %>% filter(curs >= 2025),
      aes(y = personal_disponible),
      size = 1.5,
      linetype = "dotted",
      color = paleta_ivalua[1]) +
    geom_segment(
      data = last_obs %>% 
        filter(personal_necessari > personal_disponible),
      aes(x = curs, xend = curs,
          y = personal_necessari, yend = personal_disponible),
      color = paleta_ivalua[10],
      size = 1.2) +
    geom_point(
      data = last_obs %>% 
        filter(personal_necessari > personal_disponible),
      aes(x = curs,
          y = personal_necessari),
      color = paleta_ivalua[10],
      size = 4) +
    geom_point(
      data = last_obs %>% 
        filter(personal_necessari > personal_disponible),
      aes(x = curs,
          y = personal_disponible),
      color = paleta_ivalua[10],
      size = 4) +
    geom_line(
      data = dades_filtrades %>% filter(curs <= 2025),
      aes(y = personal_disponible, color = "Personal disponible"),
      size = 1.5) +
    geom_line(
      data = dades_filtrades %>% filter(curs >= 2025),
      aes(y = personal_necessari),
      size = 1.5,
      color = paleta_ivalua[10],
      linetype = "dotted") +
    geom_line(
      data = dades_filtrades %>% filter(curs <= 2025),
      aes(y = personal_necessari, color = "Personal necessari"),
      size = 1.5) +
    scale_color_manual(values = c("Personal necessari" =  paleta_ivalua[10],
                                  "Personal disponible" = paleta_ivalua[1])) +
    geom_ribbon(
      data = dades_filtrades %>% filter(personal_disponible < personal_necessari),
      aes(ymin = personal_necessari, ymax = personal_disponible),
                fill = paleta_ivalua[11], alpha = .3) +
    scale_y_continuous(limits = c(
      (min(min(dades_filtrades$personal_disponible), min(dades_filtrades$personal_necessari))),
      (max(max(dades_filtrades$personal_disponible), max(dades_filtrades$personal_necessari))))) +
    theme_ivalua(axis_text_y = T) +
    labs(color = "") +
    scale_x_continuous(breaks = seq(0,10000,1)) +
    theme(legend.text = element_text(size = 16),
          axis.text.x = element_text(
            size = 14,
            angle = 45, vjust = 1, hjust = 1),
          axis.text.y = element_text(size = 14),
          strip.text.x = element_text(size = 20),
          ) +
    scale_y_continuous(expand = expansion(mult = c(0.2, 0.2))) +
    facet_wrap(~nivell) 
    
    

    
})
```


# Gràfic per especialitat

```{r}
plotOutput("grafic_especialitat")
```

```{r}
#| context: server

output$grafic_especialitat <- renderPlot({
  
  req(input$curs_range)
  
  validate(
    need(length(input$especialitat_filter) > 0, "Si us plau, selecciona almenys una especialitat per veure el gràfic.")
  )

  
  # Filtrar les dades segons els inputs seleccionats
  dades_filtrades <- panell %>%
    filter(ratio == input$ratio_filter,
           escenari_entrada == input$escenari_entrada_filter,
           escenari_alumnes  == input$escenari_alumnes_filter,
           concertada_privada == input$concertada_filter,
           especialitat %in% input$especialitat_filter,
           curs >= input$curs_range[1],
           curs <= input$curs_range[2])
  
  last_obs <- dades_filtrades %>% 
      filter(curs == max(curs))
  
  
  
  # Crear el gràfic amb ggplot
  dades_filtrades %>%
    ggplot(aes(x = curs)) +
    geom_line(
      data = dades_filtrades %>% filter(curs >= 2025),
      aes(y = personal_disponible),
      size = 1.5,
      linetype = "dotted",
      color = paleta_ivalua[1]) +
    geom_segment(
      data = last_obs %>% 
        filter(personal_necessari > personal_disponible),
      aes(x = curs, xend = curs,
          y = personal_necessari, yend = personal_disponible),
      color = paleta_ivalua[10],
      size = 1.2) +
    geom_point(
      data = last_obs %>% 
        filter(personal_necessari > personal_disponible),
      aes(x = curs,
          y = personal_necessari),
      color = paleta_ivalua[10],
      size = 8,
      shape = 95) +
    geom_point(
      data = last_obs %>% 
        filter(personal_necessari > personal_disponible),
      aes(x = curs,
          y = personal_disponible),
      color = paleta_ivalua[10],
      size = 8,
      shape = 95) +
    geom_line(
      data = dades_filtrades %>% filter(curs <= 2025),
      aes(y = personal_disponible, color = "Personal disponible"),
      size = 1.5) +
    geom_line(
      data = dades_filtrades %>% filter(curs >= 2025),
      aes(y = personal_necessari),
      size = 1.5,
      color = paleta_ivalua[10],
      linetype = "dotted") +
    geom_line(
      data = dades_filtrades %>% filter(curs <= 2025),
      aes(y = personal_necessari, color = "Personal necessari"),
      size = 1.5) +
    scale_color_manual(values = c("Personal necessari" =  paleta_ivalua[10],
                                  "Personal disponible" = paleta_ivalua[1])) +
    geom_ribbon(
      data = dades_filtrades %>% filter(personal_disponible < personal_necessari),
      aes(ymin = personal_necessari, ymax = personal_disponible),
                fill = paleta_ivalua[11], alpha = .3) +
    theme_ivalua(axis_text_y = T) +
    labs(color = "") +
    facet_wrap(~especialitat,
               scales = "free_y",
               ncol = 3) +
    scale_x_continuous(breaks = seq(0,10000,2)) +
    theme(legend.text = element_text(size = 16),
          axis.text.x = element_text(size = 12),
          axis.text.y = element_text(size = 12)) 

    
})
```

# Dades totals
```{r}
gt_output("dades_total")
```


```{r}
#| context: server
output$dades_total <- render_gt({
  
  req(input$curs_range)
  
  # Filtrar les dades segons els inputs seleccionats
  dades_filtrades <- panell_tot %>%
    filter(ratio == input$ratio_filter,
           escenari_entrada == input$escenari_entrada_filter,
           escenari_alumnes  == input$escenari_alumnes_filter,
           concertada_privada == input$concertada_filter,
           curs >= input$curs_range[1],
           curs <= input$curs_range[2]) %>% 
    ungroup()
  
  # Crear la taula amb gt
  dades_filtrades %>%
    select(curs, nivell, personal_disponible, personal_necessari) %>%
    mutate(
      diferencia = personal_disponible - personal_necessari,
      percentatge_cobertura = round((personal_disponible / personal_necessari) * 100, 1)
    ) %>%
    gt() %>% 
    tab_header(
      title = "Previsió de professorat en total",
      subtitle = paste("Cursos", min(dades_filtrades$curs), "a", max(dades_filtrades$curs))
    ) %>%
    cols_label(
      curs = "Curs",
      nivell = "Nivell",
      personal_disponible = "Personal disponible",
      personal_necessari = "Personal necessari",
      diferencia = "Diferència",
      percentatge_cobertura = "% Cobertura"
    ) %>%
    fmt_number(
      columns = c(personal_disponible, personal_necessari, diferencia),
      decimals = 0
    ) %>%
    fmt_number(
      columns = percentatge_cobertura,
      decimals = 1,
      suffix = "%"
    ) %>%
    data_color(
      columns = diferencia,
      colors = function(x) {
        ifelse(x >= 0,
               scales::col_numeric(palette = c("#e5e4e4", "#74b2c0"),
                                 domain = c(0, max(x[x >= 0], na.rm = TRUE)))(x),
               scales::col_numeric(palette = c("#C0001B", "#fac5c5"),
                                 domain = c(min(x[x < 0], na.rm = TRUE), 0))(x))
      }
    ) %>%
    data_color(
      columns = percentatge_cobertura,
      colors = function(x) {
        # Centrar en 100% (cobertura perfecta)
        ifelse(x >= 100,
               scales::col_numeric(palette = c("#e5e4e4", "#74b2c0"),
                                 domain = c(100, max(x[x >= 100], na.rm = TRUE)))(x),
               scales::col_numeric(palette = c("#C0001B", "#fac5c5"),
                                 domain = c(min(x[x < 100], na.rm = TRUE), 100))(x))
      }
    ) %>%
    tab_style(
      style = cell_text(weight = "bold", align = "center"),
      locations = cells_column_labels()
    ) %>%
    tab_style(
      style = cell_fill(color = "#F5F5F5"),
      locations = cells_column_labels()
    ) %>%
    tab_style(
      style = cell_text(align = "center"),
      locations = cells_body()
    ) %>%
    opt_interactive(
      use_pagination = TRUE,
      use_sorting = TRUE,
      use_search = TRUE,
      page_size_default = 20
    )
})
```






# Dades per especialitat
```{r}
gt_output("dades_especialitat")
```


```{r}
#| context: server
output$dades_especialitat <- render_gt({
  
  req(input$curs_range)
  
  # Filtrar les dades segons els inputs seleccionats
  dades_filtrades <- panell %>%
    filter(ratio == input$ratio_filter,
           escenari_entrada == input$escenari_entrada_filter,
           escenari_alumnes == input$escenari_alumnes_filter,
           concertada_privada == input$concertada_filter,
           especialitat %in% input$especialitat_filter,
           curs >= input$curs_range[1],
           curs <= input$curs_range[2]) %>%
    arrange(especialitat, curs)
  
  # Crear la taula amb gt
  dades_filtrades %>%
    select(curs, especialitat, personal_disponible, personal_necessari) %>%
    mutate(
      diferencia = personal_disponible - personal_necessari,
      percentatge_cobertura = round((personal_disponible / personal_necessari) * 100, 1)
    ) %>%
    gt() %>%
    tab_header(
      title = "Previsió de professorat per especialitat",
      subtitle = paste("Cursos", min(dades_filtrades$curs), "a", max(dades_filtrades$curs))
    ) %>%
    cols_label(
      curs = "Curs",
      especialitat = "Especialitat",
      personal_disponible = "Personal disponible",
      personal_necessari = "Personal necessari",
      diferencia = "Diferència",
      percentatge_cobertura = "% Cobertura"
    ) %>%
    fmt_number(
      columns = c(personal_disponible, personal_necessari, diferencia),
      decimals = 0
    ) %>%
    fmt_number(
      columns = percentatge_cobertura,
      decimals = 1,
      suffix = "%"
    ) %>%
    data_color(
      columns = diferencia,
      colors = function(x) {
        ifelse(x >= 0, 
               scales::col_numeric(palette = c("#e5e4e4", "#74b2c0"), 
                                 domain = c(0, max(x[x >= 0], na.rm = TRUE)))(x),
               scales::col_numeric(palette = c("#C0001B", "#fac5c5"), 
                                 domain = c(min(x[x < 0], na.rm = TRUE), 0))(x))
      }
    ) %>%
    data_color(
      columns = percentatge_cobertura,
      colors = function(x) {
        # Centrar en 100% (cobertura perfecta)
        ifelse(x >= 100, 
               scales::col_numeric(palette = c("#e5e4e4", "#74b2c0"), 
                                 domain = c(100, max(x[x >= 100], na.rm = TRUE)))(x),
               scales::col_numeric(palette = c("#C0001B", "#fac5c5"), 
                                 domain = c(min(x[x < 100], na.rm = TRUE), 100))(x))
      }
    ) %>%
   tab_style(
      style = cell_text(weight = "bold", align = "center"),
      locations = cells_column_labels()
    ) %>%
    tab_style(
      style = cell_fill(color = "#F5F5F5"),
      locations = cells_column_labels()
    ) %>%
    tab_style(
      style = cell_text(align = "center"),
      locations = cells_body()
    ) %>%
    opt_interactive(
      use_pagination = TRUE,
      use_sorting = TRUE,
      use_search = TRUE,
      page_size_default = 20
    )
})
```